CREATE SEQUENCE SEQ_CURSO
  INCREMENT 1
  MINVALUE 1
  START 1
;

CREATE SEQUENCE SEQ_TIPO_USUARIO
  INCREMENT 1
  MINVALUE 1
  START 1
;

CREATE SEQUENCE SEQ_USUARIO
  INCREMENT 1
  MINVALUE 1
  START 1
;

CREATE SEQUENCE SEQ_CURSO_USUARIO
  INCREMENT 1
  MINVALUE 1
  START 1
;

CREATE TABLE CURSO
(
	ID_CURSO bigint NOT NULL DEFAULT nextval('SEQ_CURSO'),
	DESCRICAO varchar(50),
	EMENTA text
);

ALTER TABLE CURSO ADD CONSTRAINT PK_CURSO
	PRIMARY KEY (ID_CURSO)
;

CREATE TABLE TIPO_USUARIO
(
	ID_TIPO_USUARIO bigint NOT NULL DEFAULT nextval('SEQ_TIPO_USUARIO'),
	NOME_TIPO_USUARIO varchar(50),
	DESCRICAO varchar(500)
);

ALTER TABLE TIPO_USUARIO ADD CONSTRAINT PK_TIPO_USUARIO
	PRIMARY KEY (ID_TIPO_USUARIO)
;

CREATE TABLE USUARIO
(
	ID_USUARIO bigint NOT NULL DEFAULT nextval('SEQ_USUARIO'),
	NOME varchar(50),
	EMAIL varchar(50),
	SENHA varchar(50),
	FOTO varchar(2000),
	ID_TIPO_USUARIO bigint
);

ALTER TABLE USUARIO ADD CONSTRAINT PK_USUARIO
	PRIMARY KEY (ID_USUARIO)
;

ALTER TABLE USUARIO ADD CONSTRAINT FK_TIPO_USUARIO
	FOREIGN KEY (ID_TIPO_USUARIO)
	REFERENCES TIPO_USUARIO(ID_TIPO_USUARIO)
;

CREATE TABLE CURSO_USUARIO
(
	ID_CURSO_USUARIO bigint NOT NULL DEFAULT nextval('SEQ_CURSO_USUARIO'),
	ID_CURSO bigint,
	ID_USUARIO bigint
);

ALTER TABLE CURSO_USUARIO ADD CONSTRAINT PK_CURSO_USUARIO
	PRIMARY KEY (ID_CURSO_USUARIO)
;

ALTER TABLE CURSO_USUARIO ADD CONSTRAINT FK_CURSO
	FOREIGN KEY (ID_CURSO)
	REFERENCES CURSO(ID_CURSO)
;

ALTER TABLE CURSO_USUARIO ADD CONSTRAINT FK_USUARIO
	FOREIGN KEY (ID_USUARIO)
	REFERENCES USUARIO(ID_USUARIO)
;